@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue May 05 15:07:20 +0200 2026
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto dde12ce7f76440ba8b47f9373f140783 --incr --debug typical --relax --mt 2 -L work -L secureip --snapshot tb_zybo_ps1_top_behav work.tb_zybo_ps1_top -log elaborate.log"
call xelab  -wto dde12ce7f76440ba8b47f9373f140783 --incr --debug typical --relax --mt 2 -L work -L secureip --snapshot tb_zybo_ps1_top_behav work.tb_zybo_ps1_top -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
