# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/git/DIDE/dide_fs26/zybo_ps1/vivado/zybo_ps1.cache/wt [current_project]
set_property parent.project_path C:/git/DIDE/dide_fs26/zybo_ps1/vivado/zybo_ps1.xpr [current_project]
set_property default_lib work [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/git/DIDE/dide_fs26/zybo_ps1/vivado/zybo_ps1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library work C:/git/DIDE/dide_fs26/zybo_ps1/vivado/zybo_ps1.srcs/sources_1/imports/audio/ton_gen.vhd
read_vhdl -vhdl2008 -library work {
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/pkg/ac_ssm2603_pkg.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/pkg/ap_design_pkg.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_codec/ac_i2c_master.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_codec/ac_i2c_wrapper.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_codec/ac_i2c_if.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_codec/ac_i2s_if.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_codec/ap_codec_if.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/pkg/ap_fir_pkg.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_user/fir/fir_trn.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_user/fir/fir_sel.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_user/audio/audio_ram.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_user/seg/enc_decoder.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_user/seg/seg7_driver.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_user/ap_user_top.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_clk_rst/clk_gen.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_clk_rst/rst_gen.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/ap_clk_rst/clk_rst_gen.vhd
  C:/git/DIDE/dide_fs26/zybo_ps1/vhdl/zybo_ps1_top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/git/DIDE/dide_fs26/zybo_ps1/ctrl/ap_top.xdc
set_property used_in_implementation false [get_files C:/git/DIDE/dide_fs26/zybo_ps1/ctrl/ap_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top zybo_ps1_top -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zybo_ps1_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zybo_ps1_top_utilization_synth.rpt -pb zybo_ps1_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
