-------------------------------------------------------------------------------
-- Project: DIDE Audio Processing
-- Entity : ap_design_pkg
-- Author : Waj
-------------------------------------------------------------------------------
-- Description:
-- Contains definition for audio processig design.
-- Notes:
-- * 
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;

-------------------------------------------------------------------------------
package ap_design_pkg is

  -----------------------------------------------------------------------------
  -- Word width constants
  -----------------------------------------------------------------------------
  -- configured in SSM2603 register R7, field WL, supported values: 16/24 bit
  constant ADC_DW : natural := 16;  -- ADC data width
  constant DAC_DW : natural := 16;  -- DAC data width

  -----------------------------------------------------------------------------
  -- Clocking related constants for I2S interface
  -----------------------------------------------------------------------------
  -- Primary ------------------------------------------------------------------
  constant FS_KHZ   : natural :=    48;   -- sample frequency [kHz], supported values: 48/96
                                          -- configured in SSM2603 register R8, field SR 
  constant MCLK_KHZ : natural := 12288;   -- AC master clock frequency [kHz]
                                          -- generated by MMCM #2 in clk_gen.vhd
  -- Derived ------------------------------------------------------------------
  constant BCNT_MAX : natural := MCLK_KHZ/FS_KHZ; -- max. bit count value in I2S interface
  constant BCNT_BIT : natural := natural(ceil(log2(real(BCNT_MAX)))); -- # bits of BCNT

  -----------------------------------------------------------------------------
  -- ADC/DAC data records
  -----------------------------------------------------------------------------
  type t_adc_smpl is record
    l : signed(ADC_DW-1 downto 0);
    r : signed(ADC_DW-1 downto 0);
  end record;
  type t_dac_smpl is record
    l : signed(DAC_DW-1 downto 0);
    r : signed(DAC_DW-1 downto 0);
  end record;

  -----------------------------------------------------------------------------
  -- Audio Codec records
  -----------------------------------------------------------------------------
  type t_codec_mode_sel is (
    codec_mode_analog_loopback,
    codec_mode_digital_line,
    codec_mode_digital_mic
  );
  
  -----------------------------------------------------------------------------
  -- Simulation constants
  -----------------------------------------------------------------------------
  constant TS_US : time := 1000 us/FS_KHZ;  -- ADC/DAC sample period in [us]

  -----------------------------------------------------------------------------
  -- Utility Functions
  -----------------------------------------------------------------------------

  -----------------------------------------------------------------------------
  -- fix-point math (w = total number of bits, f = number of fractional bits, w >= f!)
  -----------------------------------------------------------------------------
  ---------------------------------- fix-point add with carry bit generation --
  -- # of fractional bits of sum fs := max(fa,fb)
  -- # of total bits of sum      ws := fs + max(wa-fa,wb-fb) + 1
  function f_add(a : unsigned; fa : natural;
                 b : unsigned; fb : natural) return unsigned;
  function f_add(a : signed; fa : natural;
                 b : signed; fb : natural) return signed;
  ----------------------------------------------------- fix-point saturation --
  -- # of fractional bits of result fr := fa
  -- # of total bits of result      wr := wr
  function f_sat(a : unsigned; wr : natural) return unsigned;
  function f_sat(a : signed; wr : natural) return signed;
  ------------------------------------------------------- fix-point rounding --
  -- # of total bits of result wr := wr
  function f_rnd(a : unsigned; wr : natural) return unsigned;
  function f_rnd(a : signed; wr : natural) return signed;

end package ap_design_pkg;
-------------------------------------------------------------------------------

package body ap_design_pkg is
-------------------------------------------------------------------------------

  ------------------------------------------------------------------------------
  -- local subprograms
  -------------------------------------------------------------------------------
  function f_max(a, b : integer) return integer is
  begin
    if a > b then
      return a;
    else
      return b;
    end if;
  end f_max;

  -----------------------------------------------------------------------------
  -- fix-point math (w = total number of bits, f = number of fractional bits, w >= f!)
  -----------------------------------------------------------------------------
  ------------------------- unsigned fix-point add with carry bit generation --
  function f_add(a : unsigned; fa : natural; b : unsigned; fb : natural) return unsigned is
    constant wa  : natural := a'length;
    constant wb  : natural := b'length;
    constant fs  : natural := f_max(fa, fb);
    constant ws  : natural := fs + f_max(wa-fa, wb-fb) + 1;
    variable v_a : unsigned(ws-1 downto 0);
    variable v_b : unsigned(ws-1 downto 0);
  begin
    -- check fix-point format of operands
    assert wa >= fa report "Invalid fix-point format on operand a of f_add!" severity failure;
    assert wb >= fb report "Invalid fix-point format on operand b of f_add!" severity failure;
    -- init for zero-padding and MSB extension
    v_a := (others => '0');
    v_b := (others => '0');
    -- assign with zero-padding
    v_a(fs-fa+wa-1 downto fs-fa) := a;
    v_b(fs-fb+wb-1 downto fs-fb) := b;
    -- perform add with carry
    return v_a + v_b;
  end f_add;
  --------------------------- signed fix-point add with carry bit generation --
  function f_add(a : signed; fa : natural; b : signed; fb : natural) return signed is
    constant wa  : natural := a'length;
    constant wb  : natural := b'length;
    constant fs  : natural := f_max(fa, fb);
    constant ws  : natural := fs + f_max(wa-fa, wb-fb) + 1;
    variable v_a : signed(ws-1 downto 0);
    variable v_b : signed(ws-1 downto 0);
  begin
    -- check fix-point format of operands
    assert wa >= fa report "Invalid fix-point format on operand a of f_add!" severity failure;
    assert wb >= fb report "Invalid fix-point format on operand b of f_add!" severity failure;
    -- init for zero-padding and MSB extension
    v_a := (others => '0');
    v_b := (others => '0');
    -- assign with zero-padding
    v_a(fs-fa+wa-1 downto fs-fa) := a;
    v_b(fs-fb+wb-1 downto fs-fb) := b;
    -- sign extension a
    for k in fs-fa+wa to ws-1 loop
      v_a(k) := a(a'left);
    end loop;
    -- sign extension b
    for k in fs-fb+wb to ws-1 loop
      v_b(k) := b(b'left);
    end loop;
    -- perform add with carry
    return v_a + v_b;
  end f_add;
  -------------------------------------------- unsigned fix-point saturation --
  function f_sat(a : unsigned; wr : natural) return unsigned is
    constant wa : natural := a'length;
  begin
    -- check fix-point format of operands
    assert wr <= wa report "Result cannot have more bits than operand in f_sat!" severity failure;
    -- check valid number range
    if a = a(wr-1 downto 0) then
      -- no overflow
      return a(wr-1 downto 0);
    else
      -- overflow -> saturate to pos. maximum
      return (wr-1 downto 0 => '1');
    end if;
  end f_sat;
  ---------------------------------------------- signed fix-point saturation --
  function f_sat(a : signed; wr : natural) return signed is
    constant wa : natural := a'length;
  begin
    -- check fix-point format of operands
    assert wr <= wa report "Result cannot have more bits than operand in f_sat!" severity failure;
    -- check valid number range
    if a = a(wr-1 downto 0) then
      -- no overflow
      return a(wr-1 downto 0);
    else
      -- overflow -> saturate to pos. or neg. maximum
      if a(a'left) = '1' then
        -- neg. maximum
        return ('1' & (wr-2 downto 0 => '0'));
      else
        -- pos. maximum
        return ('0' & (wr-2 downto 0 => '1'));
      end if;
    end if;
  end f_sat;
  ------------------------------------------------- unsigned fix-point round --
  function f_rnd(a : unsigned; wr : natural) return unsigned is
    constant wa : natural := a'length;
  begin
    -- check fix-point format of operands
    assert wr < wa report "Result cannot have more bits than operand in f_rnd!" severity failure;
    -- round LSB
    if a(wa-wr-1) = '1' and a(wa-1 downto wa-wr) /= (wr-1 downto 0 => '1') then
      return f_add(shift_right(a,wa-wr),0,to_unsigned(1,1),0)(wr-1 downto 0);
    else
      return shift_right(a,wa-wr)(wr-1 downto 0);
    end if;
  end f_rnd;
----------------------------------------------------- signed fix-point round --  
  function f_rnd(a : signed; wr : natural) return signed is
    constant wa : natural := a'length;
  begin
    -- check fix-point format of operands
    assert wr < wa report "Result cannot have more bits than operand in f_rnd!" severity failure;
    assert wa > 2 report "Operand must have more than 2 bits in f_rnd!" severity failure;
    assert wr > 1 report "Result must have more than 1 bit in f_rnd!" severity failure;
    -- rounding behaviour: positive numbers in the direction of +inf and negative numbers in the direction of -inf
    if a > 0 then
      if a(wa-wr-1) = '1' and a(wa-2 downto wa-wr) /= (wr-1 downto 0 => '1') then
        return f_add(shift_right(a,wa-wr),0,to_signed(1,2),0)(wr-1 downto 0);
      else
        return shift_right(a,wa-wr)(wr-1 downto 0);
      end if;
    else
      if wa-wr >= 2 then
        if a(wa-wr-1) = '1' and unsigned(a(wa-wr-2 downto 0)) /= 0 then
          return f_add(shift_right(a,wa-wr),0,to_signed(1,2),0)(wr-1 downto 0);
        else
          return shift_right(a,wa-wr)(wr-1 downto 0);
        end if;
      else
        if a(wa-wr-1) = '1' then
          return f_add(shift_right(a,wa-wr),0,to_signed(1,2),0)(wr-1 downto 0);
        else
          return shift_right(a,wa-wr)(wr-1 downto 0);
        end if;
      end if;
    end if;
  end f_rnd;

end package body ap_design_pkg;