-------------------------------------------------------------------------------
-- Project: DIDE Audio Processing
-- Entity : ac_i2s_if
-- Author : Waj
-------------------------------------------------------------------------------
-- Description:
-- Parallel-to-serial conversion (for DAC output) and serial-to-parallel conversion 
-- (for ADC input) between I2S audio codec interface and user interface.
-- Notes:
-- * Logic clocked with BCLK is not reset. The corresponding register signals are
--   initialized to enable simulation.
-- * Only the data_enb and its synchronization registers clocked on SYS_CLK
--   are reset with rst_sys to prevent any artefact on adc/dac_enb_po propagated
--   to user logic.
-- * The SSM2603 assumes, that serial data to/from the audio codec (PBDAT/RECDAT)
--   is sampled with the rising edge and launched with the falling edge of BCLK
--   (see Timing Diagram in Figure 3).
-- * data_enb is delayed exactly 3 SYS_CLK cycles from the the first rising-edge
--   of SYS_CLK after the rsing edge of smpl_enb, which is generated by BCLK.
-------------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.ap_design_pkg.all;

entity ac_i2s_if is
  port (
    clk_sys_pi : in  std_logic;  -- 100 MHz system clock input
    rst_sys_pi : in  std_logic;  -- active high system reset
    -- I2S audio interface: codec side
    ac_bclk_pi   : in  std_logic;
    ac_pbdat_po  : out std_logic;
    ac_pblrc_po  : out  std_logic;
    ac_recdat_pi : in  std_logic;
    ac_reclrc_po : out  std_logic; 
    -- I2S audio interface: user side
    adc_data_po  : out t_adc_smpl;
    adc_enb_po   : out std_logic;
    dac_data_pi  : in t_dac_smpl; 
    dac_enb_po   : out std_logic
  );
end entity ac_i2s_if;

architecture rtl of ac_i2s_if is
 
  -- signals registerd with BCLK
  signal bcnt_regb      : unsigned(BCNT_BIT - 1 downto 0) := (others => '0'); -- bit counter
  signal lrc_regb       : std_logic;  -- left/right channel
  signal smpl_enb_regb  : std_logic;  -- data sample enable, base for adc/dac_enb
  signal dac_smpl_regb : t_dac_smpl; -- lef/right DAC sample from user logic (BCLK)
  signal adc_smpl_regb : t_adc_smpl; -- lef/right ADC sample to user logic (BCLK)
  signal dac_shft_regb  : std_logic_vector(DAC_DW-1 downto 0); -- shift register (for ac_pbdat_po)
  signal adc_shft_regb  : std_logic_vector(ADC_DW-1 downto 0); -- shift register (for ac_recdat_pi)
  -- signals registered with SYS_CLK
  signal sync_regs : std_logic_vector(3 downto 0); -- sync for CDC of sample enable
  signal data_enb_regs  : std_logic;                -- data enable = adc/dac_enb
  signal dac_smpl_regs : t_dac_smpl; -- lef/right DAC sample from user logic (SYS_CLK))
  signal adc_smpl_regs : t_adc_smpl; -- lef/right ADC sample to user logic (SYS_CLK)

begin

  -- Output assignments to audio codec
  ac_pblrc_po  <= lrc_regb;
  ac_pbdat_po  <= dac_shft_regb(dac_shft_regb'high);
  ac_reclrc_po <= lrc_regb;

  -- Output assignments to user logic
  dac_enb_po  <= data_enb_regs;
  adc_enb_po  <= data_enb_regs;
  adc_data_po <= adc_smpl_regs;

  -----------------------------------------------------------------------------
  -- Common ADC/DAC I2S infrastructure 
  -----------------------------------------------------------------------------  
  -- logic running on falling-edge of BCLK, no reset ---------------------------
  P_infra_b: process(ac_bclk_pi)
  begin
    if falling_edge(ac_bclk_pi) then
      -- Free-running BCLK counter (Fs = 48/96 kHZ -> 0..255/127; )
      bcnt_regb <= bcnt_regb + 1;
      -- left/right channel signal generated
      if bcnt_regb = BCNT_MAX/2-1 then
        lrc_regb <= '1';
      elsif bcnt_regb = BCNT_MAX-1 then
        lrc_regb <= '0';
      end if;
      -- set data sample enable '1' for last BCLK cycle
      smpl_enb_regb <= '0';
      if bcnt_regb = BCNT_MAX-2 then
        smpl_enb_regb <= '1';
      end if;
    end if;
  end process;
  -- logic on rising-edge of SYS_CLK, system reset -----------------------
  P_infra_s: process(clk_sys_pi, rst_sys_pi)
  begin
    if rst_sys_pi = '1' then
      sync_regs     <= (others => '0');
      data_enb_regs <= '0';
    elsif rising_edge(clk_sys_pi) then
      -- double-sync + 1 delay + rising-edge detect for sample enable from BCLK domain
      sync_regs(0) <= smpl_enb_regb;          -- set max. delay constraint (C0)
      sync_regs(3 downto 1) <= sync_regs(2 downto 0);
      -- rising-edge detection
      data_enb_regs <= '0';
      if sync_regs(3) = '0' and sync_regs(2) = '1' then
        data_enb_regs <= '1';
      end if;
    end if;
  end process;

  -----------------------------------------------------------------------------
  -- Parallel to serial conversion process for DAC data (SYS_CLK --> BCLK)
  ----------------------------------------------------------------------------- 
  -- logic on rising-edge of SYS_CLK, system reset ----------------------------
  P1_par2ser: process(clk_sys_pi, rst_sys_pi)
  begin
    if rst_sys_pi = '1' then
      dac_smpl_regs.l <= (others => '0');
      dac_smpl_regs.r <= (others => '0');
    elsif rising_edge(clk_sys_pi) then
      if data_enb_regs = '1' then
        -- register sample from user logic with data_enb of SYS_CLK
        dac_smpl_regs <= dac_data_pi;      
      end if;
    end if;
  end process;
  -- logic running on falling-edge of BCLK, no reset --------------------------- 
  P2_par2ser: process(ac_bclk_pi)
  begin
    if falling_edge(ac_bclk_pi) then
       -- register sample from SYS_CLK with BCLK 
       if smpl_enb_regb = '1' then
          dac_smpl_regb <= dac_smpl_regs;     -- set max. delay constraint (C1)
       end if;
      -- assign DAC sample to shift register for bit-serial output to AC
      if bcnt_regb = 0  then
        -- load shift reg with left sample during low-phase of left/right signal 
        dac_shft_regb <= std_logic_vector(dac_smpl_regb.l);
      elsif bcnt_regb = BCNT_MAX/2 then
        -- load shift reg with right sample during high-phase of left/right signal
        dac_shft_regb <= std_logic_vector(dac_smpl_regb.r); 
      else
        -- shift MSB out of shift reg
        dac_shft_regb(dac_shft_regb'high downto 1) <= dac_shft_regb(dac_shft_regb'high-1 downto 0);
      end if;
    end if;
  end process;

  -----------------------------------------------------------------------------
  -- Serial to parallel conversion process for ADC data (BCLK --> SYS_CLK)
  -----------------------------------------------------------------------------  
  P1_ser2par: process(ac_bclk_pi)
  -- logic running on rising-edge of BCLK, no reset ---------------------------  
  begin
    if rising_edge(ac_bclk_pi) then
      -- read ADC samples to shift register for parallel output to user logic
      if bcnt_regb >= 1 and bcnt_regb <= ADC_DW then
        -- shift current bit into LSB-position of shift reg (left sample)
        adc_shft_regb(0) <=  ac_recdat_pi;
        adc_shft_regb(adc_shft_regb'high downto 1) <= adc_shft_regb(adc_shft_regb'high-1 downto 0);
      elsif bcnt_regb >= BCNT_MAX/2 + 1 and bcnt_regb <= BCNT_MAX/2 + ADC_DW then
        -- shift current bit into LSB-position of shift reg (rightt sample)
        adc_shft_regb(0) <= ac_recdat_pi;
        adc_shft_regb(adc_shft_regb'high downto 1) <= adc_shft_regb(adc_shft_regb'high-1 downto 0);        
      end if;
    end if;
  end process;
  -- logic running on falling-edge of BCLK, no reset --------------------------
  P2_ser2par: process(ac_bclk_pi)
  begin
    if falling_edge(ac_bclk_pi) then
     if bcnt_regb = BCNT_MAX/2 - 2 then
        -- store shift reg to left sample at end of low-phase of left/right signal
        adc_smpl_regb.l <= signed(adc_shft_regb); 
     elsif bcnt_regb = BCNT_MAX - 2 then
        -- store shift reg to right sample at end of high-phase of left/right signal
        adc_smpl_regb.r <= signed(adc_shft_regb); 
      end if;
    end if;
  end process;
  -- logic on rising-edge of SYS_CLK, system reset -----------------------------
  P3_ser2par: process(clk_sys_pi, rst_sys_pi)
  begin
    if rst_sys_pi = '1' then
      adc_smpl_regs.l <= (others => '0');
      adc_smpl_regs.r <= (others => '0');
    elsif rising_edge(clk_sys_pi) then
      if data_enb_regs = '1' then
        -- register sample from BCLK with data_enb of SYS_CLK
        adc_smpl_regs <= adc_smpl_regb;         -- set max. delay constraint (C2)
      end if;
    end if;
  end process;

end architecture rtl;
